name: Release

on:
  push:
    branches: [ "master" ]


jobs:
  build-and-release:
    name: build, pack and release
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: dotnet/nbgv@master
      with:
        setAllVars: true
    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
    
    - name: Restore dependencies
      run: dotnet restore --no-cache
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack ./src/CanCakar.AKSReader/CanCakar.AKSReader.csproj -c Release -o artifacts --include-symbols --include-source -p:Version=${{ env.NBGV_SemVer2 }}
    - name: Publish
      run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
    - name: Github Release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create v${{ env.NBGV_SemVer2 }} --title v${{ env.NBGV_SemVer2 }} --generate-notes
      
