name: PR Validation

on:
  pull_request:
    branches: [ dev, master ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release -p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
